---
- name: "Add Noe.js from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -

- name: "Install Node.js 12"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
